# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [3]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [5]:
### [your code here]
print(np.__version__)
# print(np.version.version) # same with different syntax

#upgrading my numpy
!pip install numpy --upgrade
print(np.version.version) # still print the old version(??)

2.2.3
Defaulting to user installation because normal site-packages is not writeable
2.2.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [7]:
### [your code here]
import random

# using random list
x = [random.randint(0,100) for i in range(30)] # total number of elements
y = [random.randint(0,100) for i in range(6)] 

a = np.array(x).reshape(2,3,5)
print(a)
print('a: number of dimensions :', a.ndim, 'shape :', a.shape)

# using randint directly
b = np.random.randint(0,100, size=(2,3,5))
print(b)
print('b: number of dimensions :', b.ndim, 'shape :', b.shape)

# using random
c = np.random.rand(2,3,5)
print(c)
print('c: number of dimensions :', c.ndim, 'shape :', c.shape)

# .array() with premade list
z = [[[random.randint(0,100) for i in range(5)] for j in range(3)] for k in range(2)] 
d = np.array(z, ndmin=3)
print(d)
print('d: number of dimensions :', d.ndim, 'shape :', d.shape)


# b = np.full((2,3,5), y) # same val on each line -> error if y > n (lowest dimension val)
# print(b)
# print('number of dimensions :', b.ndim)


# c = np.array([1, 2, 3, 4], ndmin=3) # creates matrioshka
# print(c)
# print('number of dimensions :', c.ndim)



[[[54  9 24  8 46]
  [ 0 93 70 19 82]
  [52 30 96 93 73]]

 [[63 77 35 18 28]
  [97 39 89 59 68]
  [39 58 84 57 18]]]
a: number of dimensions : 3 shape : (2, 3, 5)
[[[23 51 77  4 26]
  [13 92 48 51 58]
  [77 82 17 48 72]]

 [[ 3 51 95 71 25]
  [47 99 58 24 29]
  [73 33 11 10 72]]]
b: number of dimensions : 3 shape : (2, 3, 5)
[[[0.42802796 0.54820839 0.16059798 0.58302211 0.24424561]
  [0.35349117 0.10753617 0.12507152 0.8477803  0.29230142]
  [0.24552003 0.33062094 0.96595851 0.22591887 0.7389598 ]]

 [[0.13694553 0.01333654 0.90902438 0.62009913 0.03034124]
  [0.80345224 0.08912936 0.0858824  0.73468614 0.37371638]
  [0.44095683 0.49034316 0.09515491 0.96274613 0.43252335]]]
c: number of dimensions : 3 shape : (2, 3, 5)
[[[ 5  1 21 85 51]
  [17  7 37 74 21]
  [44 29 61 15 78]]

 [[62 14 92 81 87]
  [24 61 93 26 77]
  [81 63 57 10 22]]]
d: number of dimensions : 3 shape : (2, 3, 5)



### 4. Print a.


In [9]:
### [your code here]
print(a)

[[[54  9 24  8 46]
  [ 0 93 70 19 82]
  [52 30 96 93 73]]

 [[63 77 35 18 28]
  [97 39 89 59 68]
  [39 58 84 57 18]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [11]:
### [your code here]
b = np.ones((5,2,3))
c = np.full((5,2,3), 1)


### 6. Print b.


In [13]:
### [your code here]
print(b, "b: dimensions : ", b.ndim, " shape : ", b.shape, type(b[0,0,0]))
print(c, "c: dimensions : ", b.ndim, " shape : ", c.shape, type(b[0,0,0]))

# same type different formatting? - A: np.full fills array with a given value in float while keeping the input look(aka not adding the dot)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]] b: dimensions :  3  shape :  (5, 2, 3) <class 'numpy.float64'>
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]] c: dimensions :  3  shape :  (5, 2, 3) <class 'numpy.float64'>



### 7. Do a and b have the same size? How do you prove that in Python code?


In [15]:
### [your code here]

if a.size == b.size:
    print("Yes, sizes of a and b are equal")
else:
    print("No, a and b have different sizes")

Yes, sizes of a and b are equal



### 8. Are you able to add a and b? Why or why not?


In [17]:
### [your code here]
# print(a + b) # !different shapes - can't add <-  can add if "broadcastable"

print(a + b.reshape(2,3,5))

[[[55. 10. 25.  9. 47.]
  [ 1. 94. 71. 20. 83.]
  [53. 31. 97. 94. 74.]]

 [[64. 78. 36. 19. 29.]
  [98. 40. 90. 60. 69.]
  [40. 59. 85. 58. 19.]]]




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [19]:
### [your code here]
c = b.reshape(2,3,5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [21]:
### [your code here]
d = a + c # a and c have same dimensionality
print(d)

# broadcasting test
test_arr = np.array(z, ndmin=2)  
print(test_arr, test_arr.ndim, test_arr.shape)
# print("braodcasting check :\n",a + test_arr) # value error - 2,3,5 to 1,6 

test_arr1 = test_arr.reshape(3,2,1,5)
print(test_arr, test_arr.ndim, test_arr.shape)
print("braodcasting check :\n",a + test_arr1) # broadcasting check - from right to left dim_m(..,n,..) == dim_k(..,n,..) | dim_m(..,n,..) & dim_k(..,1,..) 


[[[55. 10. 25.  9. 47.]
  [ 1. 94. 71. 20. 83.]
  [53. 31. 97. 94. 74.]]

 [[64. 78. 36. 19. 29.]
  [98. 40. 90. 60. 69.]
  [40. 59. 85. 58. 19.]]]
[[[ 5  1 21 85 51]
  [17  7 37 74 21]
  [44 29 61 15 78]]

 [[62 14 92 81 87]
  [24 61 93 26 77]
  [81 63 57 10 22]]] 3 (2, 3, 5)
[[[ 5  1 21 85 51]
  [17  7 37 74 21]
  [44 29 61 15 78]]

 [[62 14 92 81 87]
  [24 61 93 26 77]
  [81 63 57 10 22]]] 3 (2, 3, 5)
braodcasting check :
 [[[[ 59  10  45  93  97]
   [  5  94  91 104 133]
   [ 57  31 117 178 124]]

  [[ 80  84  72  92  49]
   [114  46 126 133  89]
   [ 56  65 121 131  39]]]


 [[[ 98  38  85  23 124]
   [ 44 122 131  34 160]
   [ 96  59 157 108 151]]

  [[125  91 127  99 115]
   [159  53 181 140 155]
   [101  72 176 138 105]]]


 [[[ 78  70 117  34 123]
   [ 24 154 163  45 159]
   [ 76  91 189 119 150]]

  [[144 140  92  28  50]
   [178 102 146  69  90]
   [120 121 141  67  40]]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [23]:
### [your code here]
print("a array\n", a,"\nd array:\n", d)

if (a.shape == d.shape) & (a.ndim == d.ndim):
    print("they have equal shapes and dimensions, with d = a + 1 for each value")

a array
 [[[54  9 24  8 46]
  [ 0 93 70 19 82]
  [52 30 96 93 73]]

 [[63 77 35 18 28]
  [97 39 89 59 68]
  [39 58 84 57 18]]] 
d array:
 [[[55. 10. 25.  9. 47.]
  [ 1. 94. 71. 20. 83.]
  [53. 31. 97. 94. 74.]]

 [[64. 78. 36. 19. 29.]
  [98. 40. 90. 60. 69.]
  [40. 59. 85. 58. 19.]]]
they have equal shapes and dimensions, with d = a + 1 for each value



### 12. Multiply a and c. Assign the result to e.


In [25]:
### [your code here]
e = a*c



### 13. Does e equal to a? Why or why not?


In [27]:
### [your code here]

print(a, a.ndim, a.shape)
print(e, e.ndim, e.shape)

if np.array_equal(a,e):
    print("They are equal, becasue is e = a*c, where c contains only 1s")
else:
    print("They are not equal")


[[[54  9 24  8 46]
  [ 0 93 70 19 82]
  [52 30 96 93 73]]

 [[63 77 35 18 28]
  [97 39 89 59 68]
  [39 58 84 57 18]]] 3 (2, 3, 5)
[[[54.  9. 24.  8. 46.]
  [ 0. 93. 70. 19. 82.]
  [52. 30. 96. 93. 73.]]

 [[63. 77. 35. 18. 28.]
  [97. 39. 89. 59. 68.]
  [39. 58. 84. 57. 18.]]] 3 (2, 3, 5)
They are equal, becasue is e = a*c, where c contains only 1s




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [29]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f"For the d array:\nmax is: {d_max}\nmin is: {d_min}\nmean is: {round(d_mean)}")


For the d array:
max is: 98.0
min is: 1.0
mean is: 54



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [31]:
### [your code here]
f = np.empty(d.shape)

# print(d.shape)

# f = np.empty((2,3,5))
# print(f,"\n",d)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [33]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if (d[i,j,k] > d_min) and (d[i,j,k] < d_mean):
                f[i,j,k] = 25
            elif (d[i,j,k] > d_mean) and (d[i,j,k] < d_max):
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [35]:
### [your code here]
print(d, "\n", f)

[[[55. 10. 25.  9. 47.]
  [ 1. 94. 71. 20. 83.]
  [53. 31. 97. 94. 74.]]

 [[64. 78. 36. 19. 29.]
  [98. 40. 90. 60. 69.]
  [40. 59. 85. 58. 19.]]]
 [[[ 75.  25.  25.  25.  25.]
  [  0.  75.  75.  25.  75.]
  [ 25.  25.  75.  75.  75.]]

 [[ 75.  75.  25.  25.  25.]
  [100.  25.  75.  75.  75.]
  [ 25.  75.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.